export const availableIngredients = [
  {
    id: 1,
    name: "Тонкое тесто",
    type: "dough",
    price: 60,
    img: "img/thin_dough.jpg",
  },
  {
    id: 2,
    name: "Толстое тесто",
    type: "dough",
    price: 70,
    img: "img/thick_dough.jpg",
  },
  {
    id: 3,
    name: "Пепперони",
    type: "meat",
    price: 50,
    img: "img/pepperoni.jpg",
  },
  {
    id: 4,
    name: "Грибы",
    type: "vegetable",
    price: 30,
    img: "img/mashrooms.jpg",
  },
  {
    id: 5,
    name: "Моцарелла",
    type: "cheese",
    price: 40,
    img: "img/mozzarella_cheese.jpg",
  },
  {
    id: 6,
    name: "Помидоры",
    type: "vegetable",
    price: 25,
    img: "img/tomato.jpg",
  },
  {
    id: 7,
    name: "Ветчина",
    type: "meat",
    price: 45,
    img: "img/ham.jpg",
  },
  {
    id: 8,
    name: "Оливки",
    type: "vegetable",
    price: 35,
    img: "img/oliv.jpg",
  },
  {
    id: 9,
    name: "Сгущенное молоко",
    type: "sauce",
    price: 20,
    img: "img/condensed_milk.jpg",
  },
  {
    id: 10,
    name: "Клюква",
    type: "fruit",
    price: 30,
    img: "img/cranberry.jpg",
  },
  {
    id: 11,
    name: "Свежий огурец",
    type: "vegetable",
    price: 25,
    img: "img/cucumber.jpg",
  },
  {
    id: 12,
    name: "Соус карри",
    type: "sauce",
    price: 15,
    img: "img/curry_sauce.jpg",
  },
  {
    id: 13,
    name: "Кетчуп",
    type: "sauce",
    price: 10,
    img: "img/ketchup.jpg",
  },
  {
    id: 14,
    name: "Лук",
    type: "vegetable",
    price: 5,
    img: "img/onion.jpg",
  },
  {
    id: 15,
    name: "Майонез",
    type: "sauce",
    price: 20,
    img: "img/mayonnaise.jpg",
  },
  {
    id: 16,
    name: "Мидии",
    type: "seafood",
    price: 30,
    img: "img/mussels.jpg",
  },
  {
    id: 17,
    name: "Чеддер",
    type: "cheese",
    price: 45,
    img: "img/cheddar_cheese.jpg",
  },
  {
    id: 18,
    name: "Груша",
    type: "fruit",
    price: 30,
    img: "img/pear.jpg",
  },
  {
    id: 19,
    name: "Соус песто",
    type: "sauce",
    price: 20,
    img: "img/pesto_sauce.jpg",
  },
  {
    id: 20,
    name: "Ананас",
    type: "fruit",
    price: 35,
    img: "img/pineapple.jpg",
  },
  {
    id: 21,
    name: "Креветки",
    type: "seafood",
    price: 30,
    img: "img/shrimp.jpg",
  },
  {
    id: 22,
    name: "Пармезан",
    type: "cheese",
    price: 45,
    img: "img/parmesan_cheese.jpg",
  },
  {
    id: 23,
    name: "Острый сосус",
    type: "sauce",
    price: 20,
    img: "img/spicy_sauce.jpg",
  },
  {
    id: 24,
    name: "Кальмар",
    type: "seafood",
    price: 20,
    img: "img/squid.jpg",
  },
  {
    id: 25,
    name: "Сулугуни",
    type: "cheese",
    price: 35,
    img: "img/suluguni_cheese.jpg",
  },
  {
    id: 26,
    name: "Соус васаби",
    type: "sauce",
    price: 20,
    img: "img/wasabi_sauce.jpg",
  },
];
